// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ween.Data;

#nullable disable

namespace Ween.Migrations
{
    [DbContext(typeof(WeenContext))]
    [Migration("20260830115915_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ween.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BA4D11AEB");

                    b.HasIndex(new[] { "Slug" }, "UQ__Categori__BC7B5FB6F7AFA51D")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ween.Data.CategoryField", b =>
                {
                    b.Property<int>("CategoryFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryFieldId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Options")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryFieldId")
                        .HasName("PK__Category__213B041276F586DD");

                    b.HasIndex(new[] { "CategoryId" }, "IX_CategoryFields_Category");

                    b.ToTable("CategoryFields");
                });

            modelBuilder.Entity("Ween.Data.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("LocalName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21B76630E1DB8");

                    b.HasIndex(new[] { "Slug" }, "UQ__Cities__BC7B5FB62C359231")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Ween.Data.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hours")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2, 1)");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlaceId")
                        .HasName("PK__Places__D5222B6E06024839");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Places_Category");

                    b.HasIndex(new[] { "CityId", "CategoryId" }, "IX_Places_City_Category");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Ween.Data.PlaceFieldValue", b =>
                {
                    b.Property<int>("PlaceFieldValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceFieldValueId"));

                    b.Property<int>("CategoryFieldId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("PlaceFieldValueId")
                        .HasName("PK__PlaceFie__8A47BA3A49C1F373");

                    b.HasIndex("CategoryFieldId");

                    b.HasIndex(new[] { "PlaceId", "CategoryFieldId" }, "UQ_PlaceFieldValues")
                        .IsUnique();

                    b.ToTable("PlaceFieldValues");
                });

            modelBuilder.Entity("Ween.Data.PlacePhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("PhotoId")
                        .HasName("PK__PlacePho__21B7B5E28CC0AFDD");

                    b.HasIndex(new[] { "PlaceId" }, "IX_PlacePhotos_Place");

                    b.ToTable("PlacePhotos");
                });

            modelBuilder.Entity("Ween.Data.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("Nights")
                        .HasColumnType("int");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ReservationTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__B7EE5F247E1C2B36");

                    b.HasIndex(new[] { "PlaceId" }, "IX_Reservations_Place");

                    b.HasIndex(new[] { "UserId" }, "IX_Reservations_User");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Ween.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CE6ABAD71");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105342DB492D8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ween.Data.CategoryField", b =>
                {
                    b.HasOne("Ween.Data.Category", "Category")
                        .WithMany("CategoryFields")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoryFields_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ween.Data.Place", b =>
                {
                    b.HasOne("Ween.Data.Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Places_Categories");

                    b.HasOne("Ween.Data.City", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Places_Cities");

                    b.HasOne("Ween.Data.User", "CreatedByUser")
                        .WithMany("Places")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Places_Users");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Ween.Data.PlaceFieldValue", b =>
                {
                    b.HasOne("Ween.Data.CategoryField", "CategoryField")
                        .WithMany("PlaceFieldValues")
                        .HasForeignKey("CategoryFieldId")
                        .IsRequired()
                        .HasConstraintName("FK_PlaceFieldValues_CategoryFields");

                    b.HasOne("Ween.Data.Place", "Place")
                        .WithMany("PlaceFieldValues")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceFieldValues_Places");

                    b.Navigation("CategoryField");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Ween.Data.PlacePhoto", b =>
                {
                    b.HasOne("Ween.Data.Place", "Place")
                        .WithMany("PlacePhotos")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlacePhotos_Places");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Ween.Data.Reservation", b =>
                {
                    b.HasOne("Ween.Data.Place", "Place")
                        .WithMany("Reservations")
                        .HasForeignKey("PlaceId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Places");

                    b.HasOne("Ween.Data.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Users");

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ween.Data.Category", b =>
                {
                    b.Navigation("CategoryFields");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("Ween.Data.CategoryField", b =>
                {
                    b.Navigation("PlaceFieldValues");
                });

            modelBuilder.Entity("Ween.Data.City", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("Ween.Data.Place", b =>
                {
                    b.Navigation("PlaceFieldValues");

                    b.Navigation("PlacePhotos");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Ween.Data.User", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
